// tuning-config.js
export const TUNING_DEFAULTS = {
    "lerpSpeed": 0.69,
    "lerpDecay": 0.43,
    "resetToNeutral": 0.5,
    "maxIntensity": 1.5,
    "openMultiplier": 0.5,
    "tightMultiplier": 1.5,
    "duckMultiplier": 1.5,
    "jawBoost": 0.3,
    "tongueScale": 0.3,
    "silenceThreshold": 0.08,
    "blinkIntervalMin": 1,
    "blinkIntervalMax": 8,
    "blinkCloseDuration": 60,
    "blinkHoldDuration": 150,
    "doubleBlink": 0.15,
    "microMouthAmp": 0.4,
    "microBrowAmp": 0.8,
    "microSpeed": 4.7,
    "smileIntensity": 0.25,
    "breathAmplitude": 0.15,
    "breathSpeed": 4,
    "headDriftAmp": 0.15,
    "hairFlex": 1
};